### ISSUE TITLE
TypeError: Object of type coroutine is not JSON serializable

### ISSUE THREAD

**Issue by cremesk** [maubot/github#20]
hi, i see today an error after i updated maubot to version v0.3.1

is the github plugin broker in this maubot version?

```
[17:35:52](file:////opt/maubot/plugins/xyz.maubot.github-v0.1.1.mbp/github/webhook/aggregation.py:97)ERROR[instance/github.webhook](https://matrix.envs.net/_matrix/maubot/#/instance/github.webhook)Fatal error in aggregation handler
[17:35:52](file:////opt/maubot/plugins/xyz.maubot.github-v0.1.1.mbp/github/webhook/aggregation.py:97)ERROR[instance/github.webhook](https://matrix.envs.net/_matrix/maubot/#/instance/github.webhook)Traceback (most recent call last):
  File "/opt/maubot/plugins/xyz.maubot.github-v0.1.1.mbp/github/webhook/aggregation.py", line 101, in _start
    starter = self.aggregation_starters[self.event_type, self.event.action]
KeyError: (EventType.PUSH, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/maubot/plugins/xyz.maubot.github-v0.1.1.mbp/github/webhook/aggregation.py", line 95, in start
    await self._start()
  File "/opt/maubot/plugins/xyz.maubot.github-v0.1.1.mbp/github/webhook/aggregation.py", line 104, in _start
    await self._send()
  File "/opt/maubot/plugins/xyz.maubot.github-v0.1.1.mbp/github/webhook/aggregation.py", line 126, in _send
    await self.handler.send_message(self.event_type, self.event, self.webhook_info.room_id,
  File "/opt/maubot/plugins/xyz.maubot.github-v0.1.1.mbp/github/webhook/handler.py", line 132, in send_message
    await self.bot.client.send_message(room_id, content)
  File "/opt/maubot/lib/python3.9/site-packages/mautrix/client/encryption_manager.py", line 164, in send_message_event
    return await super().send_message_event(room_id, event_type, content, **kwargs)
  File "/opt/maubot/lib/python3.9/site-packages/mautrix/client/api/events.py", line 401, in send_message_event
    resp = await self.api.request(
  File "/opt/maubot/lib/python3.9/site-packages/mautrix/api.py", line 363, in request
    content = json.dumps(content)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
```

**Comment by tulir** [comment]
Oops, forgot to tag a new release

**Comment by cremesk** [comment]
okay no problem.
it works fine now! ;)
